[package]
name = "onnx-ms-squeeznet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onnxruntime = "0.0.14"
tracing = "0.1"
tracing-subscriber = "0.3.16"